version: "3.8"
services:
  catalogdb:
    container_name: catalogdb7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdb7_volume:/data/db
  basketdb:
    container_name: basketdb7
    restart: always
    ports:
      - "6379:6379"
  discountdb:
    container_name: discountdb7
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discount7_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iS47????
      - POSTGRES_DB=discountdb
  identitydb:
    container_name: identitydb7
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - identitydb7_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=iS47????
  orderdb:
    container_name: orderdb7
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - orderdb7_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=iS47????
  rabbitmq:
    container_name: rabbitmq7
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  catalog.api:
    container_name: catalog7.api
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development 
      - RabbitMQUrl=rabbitmq   
      - IdentityServerURL=http://identityserver.api
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    ports:
      - "5011:80" 
    depends_on:
      - catalogdb
  identityserver.api:
    container_name: identityserver7.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=identitydb,1433;Database=identityDb;User=sa;Password=iS47????"
    ports:
      - "5001:80"
    depends_on:
      - identitydb
  basket.api:
    container_name: basket7.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - RedisSettings:Port=6379
      - RedisSettings:Host=basketdb
    ports:
      - "5013:80"
    depends_on:
      - basketdb
  photostock.api:
    container_name: photostock7.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
    ports:
      - "5012:80"
    volumes:
      - type: bind
        source: C:\Users\90546\Desktop\photos
        target: /app/wwwroot/photos
  discount.api:
    container_name: discount7.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - "ConnectionStrings:PostgreSql=User ID=postgres; Password=iS47????; Server=discountdb; Port=5432;Database=discountdb;Integrated Security=true;Pooling=true"
    ports:
      - "5014:80"
    depends_on:
      - discountdb
  fakepayment.api:
    container_name: fakepayment7.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - RabbitMQUrl=rabbitmq
    ports:
      - "5016:80"
  order.api:
    container_name: order7.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - RabbitMQUrl=rabbitmq
      - "ConnectionStrings:DefaultConnection=Server=orderdb,1433;Database=OrderDb; User=sa; Password=iS47????"
    ports:
      - "5015:80"
    depends_on:
      - orderdb
  gateway.api:
    container_name: gateway7.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - IdentityServerURL=http://identityserver.api
    ports:
      - "5000:80"
  aspnetcoremvc.web:
    container_name: aspnetcoremvc7.web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceApiSettings:IdentityBaseUrl=http://identityserver.api
      - ServiceApiSettings:GatewayBaseUrl=http://gateway.api

    ports:
      - "5010:80"
    depends_on:
      - gateway.api
      - identityserver.api
      - catalog.api
      - basket.api
      - discount.api
      - order.api
      - photostock.api
      - fakepayment.api